language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
   - python -m unittest discover -s tests -v
#  - coverage run -m unittest discover -s tests -v
#  - coverage html --omit="*/tests/*"
#before_deploy:
#  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz htmlcov
#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
#  skip_cleanup: true
#  draft: true
#  on:
#    branch: master